#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Stub\Console\Parse;
use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new Parse());
$app->run();
