#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

use Stub\Console\Parse;
use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new Parse());
$app->run();
